project 'AppDemo.xcodeproj'

platform :ios, '9.0'
inhibit_all_warnings!

target 'AppDemo' do
  pod 'AFNetworking', '~> 3.1.0'
  pod 'Masonry'
  pod 'XLForm', '~> 3.2.0'
  pod 'SDWebImage'
  pod 'SVProgressHUD'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'WXWaveView', '~> 1.0'
  pod 'IQKeyboardManager'
  pod 'KMNavigationBarTransition'
  pod 'NYSTK', '~> 0.0.4'
  pod 'NYSMC', '~> 0.2.1'
  
  pod 'JPush'
  pod 'RongCloudIM'
  pod 'UMCCommon'
  pod 'UMCShare/UI'
  pod 'UMCCommonLog'
  pod 'UMCShare/Social/ReducedWeChat'
  pod 'UMCShare/Social/ReducedQQ'
  
  target 'AppDemoTests' do
    inherit! :search_paths
  end

  target 'AppDemoUITests' do
    inherit! :search_paths
  end

end
