project 'AppDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'AppDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AppDemo
  pod 'AFNetworking', '~> 3.1.0'
  pod 'Masonry'
  pod 'XLForm', '~> 3.2.0'
  pod 'SDWebImage'
  pod 'SVProgressHUD'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'WXWaveView', '~> 1.0'
  pod 'KMNavigationBarTransition'
  pod 'NYSTK', '~> 0.0.2'
  
  
  pod 'JPush', '3.1.0'
  pod 'RongCloudIM'
  pod 'UMCCommon'
  pod 'UMCShare/UI'
  pod 'UMCCommonLog'
  
  # 集成微信(精简版0.2M)
  pod 'UMCShare/Social/ReducedWeChat'
  # 集成QQ/QZone/TIM(精简版0.5M)
  pod 'UMCShare/Social/ReducedQQ'
  
  target 'AppDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
